server:
  port: 8001

spring:
  application:
    name: anproduct
  datasource:
    url: jdbc:mysql://127.0.0.1/crbook?serverTimezone=UTC&CharacterEncoding=UTF-8&useSSL=false
    username: root
    password: a
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    com.yc.crbook.dao: debug
