server:
  port: 8003

#\u5B9A\u4E49\u5F53\u524D\u670D\u52A1\u540D
spring:
  application:
    name: anuser

  datasource:
    url: jdbc:mysql://112.74.84.42/S3-Antidote?serverTimezone=UTC&CharacterEncoding=UTF-8&useSSL=false
    username: root
    password: Xkh0716!
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    com.yc.clouduser8003.dao: debug