server:
  port: 8004

spring:
  application:
    name: anblog
  datasource:
    url: jdbc:mysql://127.0.0.1/antidote?serverTimezone=UTC&CharacterEncoding=UTF-8&useSSL=false
    username: root
    password: a
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    com.yc.antidote.dao: debug