server:
  port: 80

# \u5B9A\u4E49\u5F53\u524D\u670D\u52A1\u540D
spring:
  application:
    name: anzuul

zuul:
  routes:
    test:
      path: /simple/**
      url: http://www.163.com
    #crbook: /book/**
    #cruser: /user/**
    base:
      path: /**
      serviceId: anindex
